### ISSUE TITLE
Implement Skip-to-content Link for Accessibility

### ISSUE THREAD

**Issue by Duds** [Duds/dale-rogers-portfolio#22]
### Description
Add a skip-to-content link to improve keyboard navigation and accessibility for screen reader users.

### Tasks
- [ ] Create skip link component
- [ ] Add target ID to main content
- [ ] Style skip link (hidden by default, visible on focus)
- [ ] Test with keyboard navigation
- [ ] Test with screen readers

### Technical Implementation
```typescript
interface SkipLinkProps {
  /** The ID of the main content element to skip to */
  targetId: string;
  /** Optional custom text for the skip link */
  text?: string;
}
```

### CSS Implementation
```css
.skip-link {
  position: absolute;
  top: -40px;
  left: 0;
  padding: 8px;
  background-color: var(--color-background);
  transition: top 0.2s;
}

.skip-link:focus {
  top: 0;
  z-index: 100;
}
```

### Acceptance Criteria
- Skip link appears on first tab press
- Link correctly focuses main content
- Styling follows theme system
- Works with keyboard navigation
- Screen reader announces properly

### Technical Requirements
- Follow WCAG 2.1 guidelines
- Implement proper ARIA attributes
- Add comprehensive testing
- Follow Australian English standards

### Priority
High

### Estimated Time
1 hour

### Parent Theme
Accessibility Enhancements
